resources:
  - name: src
    type: git
    source:
      uri: https://github.com/idrop/concoursetest.git
      branch: main

  - name: image
    type: docker-image
    source:
      repository: localhost:5000/concoursetest

jobs:
  - name: build-image-and-push
    plan:
      - get: src
        trigger: true
      - put: image
        params:
          build: src
#          build_args:
#            GRADLE_IMG: gradle:jdk8